name: lock

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Release version to be locked
        required: true

jobs:
  lock-or-unlock:
    runs-on: ubuntu-latest
    steps:
    - name: Run Branch Protection
      env:
        GH_TOKEN: ${{ secrets.GH_KEY }}
        REL: ${{github.event.inputs.release_version}}
      run: |
        curl -L \
        -X PUT \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GH_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/RootEduClasses/terraform/branches/release/platform-$REL/protection \
        -d '{
        "restrictions": {
            "users": [],
            "teams": []
        },
        "required_status_checks": null,
        "required_conversation_resolution": true,
        "enforce_admins": null,
        "required_pull_request_reviews":
        {
        "require_code_owner_reviews": true,
        "required_approving_review_count":2,
        "dismiss_stale_reviews": true,
        "require_last_push_approval": true,
        "bypass_pull_request_allowances": {
            "users": ["root-edu"],
            "teams": [],
            "apps": []
        }
        "lock_branch": true,
        }
        }'
