name: "Terraform infra"
on: 
  push
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
jobs: 
  Validate:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout the code to VM
         uses: actions/checkout@v3
       - name: Install terraform 
         uses: hashicorp/setup-terraform@v1
       - name: init
         run: |
             terraform init
       - name: Terraform format
         run: |
             terraform fmt
       - name: Terraform Validate
         run: |
             terraform validate
       - name: Launch Infra
         run: |
             terraform apply -auto-approve
