name: lock

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Release version to be locked
        required: false

jobs:
  lock-or-unlock:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Run Branch Protection
      env:
        GH_TOKEN: ${{ secrets.GH_KEY }}
        REL: ${{github.event.inputs.release_version}}
      run: |
        for i in `cat repos`
        do
        for j in `cat rel-versions`
        do
        curl -L \
        -X PUT \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GH_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/RootEduClasses/$i/branches/release/platform-$j/protection \
        -d '{
        "required_status_checks": null,
        "enforce_admins": null,
        "required_pull_request_reviews": {
        "dismiss_stale_reviews": true,
        "require_code_owner_reviews": true,
        "required_approving_review_count": 2,
        "require_last_push_approval": false,
        "restrictions": {
        "users": [""],
        "teams": [""]
        },
        "required_linear_history": true,
        "allow_force_pushes": false,
        "allow_deletions": false,
        "block_creations": true,
        "required_conversation_resolution": true,
        "lock_branch": true,
        "allow_fork_syncing": true
        }'
        done
        done
