name: lock-or-unlock

on:
  push:
permissions: write-all

jobs:
  lock-or-unlock:
    runs-on: ubuntu-latest
    steps:
    - name: Run Branch Protection
      env:
        GH_TOKEN: ${{ secrets.GH_KEY }}
      run: |
        curl -L \
        -X PUT \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GH_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/RootEduClasses/terraform/branches/demo/protection/restrictions \
        -d '{"restrictions":{"users":[""],"teams":[""],"apps":[""]}}'
